spring:
  application:
    name: shopping-cart-service
#  main:
#    allow-bean-definition-overriding: true
  data:
    redis:
      repositories:
        enabled: false
server:
  port: 8081
vmdev:
  pet:
    eshop:
      provider:
        cache-storage:
          redis:
            server:
              host: localhost
              port: 6379
            keyspace:
              ttl: 1h
      product-fabric:
        http:
          client:
            name: product-fabric
            url: localhost:8082/api/v1